version: '3.8'

services:
    orange-cal:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: orange-cal-bot
        restart: unless-stopped
        depends_on:
            - redis
            - mongo
        environment:
            - NODE_ENV=production
            - DISCORD_TOKEN=${DISCORD_TOKEN}
            - CLIENT_ID=${CLIENT_ID}
            - MONGO_URI=${MONGO_URI}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '3'

    redis:
        image: redis:latest
        container_name: orange-cal-redis
        restart: unless-stopped
        ports:
            - '6379:6379'
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '3'
        volumes:
            - redis-data:/data

    mongo:
        image: mongo:latest
        container_name: orange-cal-mongo
        restart: unless-stopped
        ports:
            - '27017:27017'
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '3'
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data:
        driver: local
    redis-data:
        driver: local
